#!/usr/bin/env bash
#This script prints Best School 10 times and Hi on 9th iteration

n=1

while [ $n -le 10 ]; do
if	[ $n -eq 9 ]; then
	echo "Best School"
	echo "Hi"
else
	echo "Best School"
fi
((n++))

done	
