#!/usr/bin/env bash
#Bash script loop printing 1 to 10 Best School, bad luck, good luck

n=1

while [ $n -le 9 ]; do
if [ $n -eq 3 ]; then
	echo "Best School"
	echo "bad luck"
elif [ $n -eq 7 ]; then
	echo "Best School"
	echo "good luck"
else
	echo "Best School"

fi
((n++))

done
