#!/usr/bin/env bash
#Bash script loop printing 1 to 10 Best School, bad luck, good luck

n=1

while [ $n -le 10 ]; do
if [ $n -eq 4 ]; then
	echo "Best School"
	echo "bad luck"
elif [ $n -eq 8 ]; then
	echo "Best School"
	echo "good luck"
else
	echo "Best School"
fi
((n++))

done
