#!/usr/bin/env bash
#This script prints n 1 to 20 and with lettered additions

x=1

while [ $x -le 20 ]
do
	case $x in
		1) echo "1";;
		2) echo "2";;
		3) echo "3";;
		4) echo "4";;
		4) echo "Bad luck from China";;
		5) echo "5";;
		6) echo "6";;
		7) echo "7";;
		8) echo "8";;
		9) echo "9";;
		9) echo "Bad luck from Japan";;
		10) echo "10";;
		11) echo "11";;
		12) echo "12";;
		13) echo "13";;
		14) echo "14";;
		15) echo "15";;
		16) echo "16";;
		17) echo "17";;
		17) echo "Bad luck from Italy";;
		18) echo "18";;
		19) echo "19";;
		20) echo "20";;
		
	esac
	x=$((x+1))
done
