#!/usr/bin/env bash
#This script prints n 1 to 20 and with lettered additions

x=1

while [ $x -le 20 ]
do
	echo $n
	case $n in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
