#!/usr/bin/env bash
#This displays time hours and minutes

hours=0
minutes=1

while [ $hours -le  12 ]; do
	while [ $minutes -le 59 ]; do
		printf "%02d:%02d\n" $hours $minutes
		((hours++))
		if [ $minutes -eq 60 ]; then
			minutes=0
			((minutes++))
		fi
	done
done | head -n 70
