#!/usr/bin/env bash
#This displays time hours and minutes

hour=0

while [ $hour -le  12 ]; do
		echo hour: $hour
	minute=1

	while [ $minute -le 59 ]; do
		printf "$minute"
		((minute++))
	done
		((hour++))
done
