#!/usr/bin/env bash
#This displays time hours and minutes

hours=0
minutes=1

while [ $hours -le  12 ]; do
	while [ $minutes -le 59 ]; do
		printf "%d:%d\n" $hours $minutes
		((minutes++))
		if [ $minutes -eq 60 ]; then
			minutes=0
			((hours++))
		fi
	done
done | head -n 70
