#!/usr/bin/env bash
#Script prints contents of cd in list form with part of name first dash

for file in $(ls -p | grep -v /$)
do
	base=$(basename "$file")
	after_dash=${base#-}

	echo "$after_dash"
done
